name: Build and Test Java Spring Boot Application
on: push
jobs:
  build:
    - name: Build and Test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set up JDK 20
          uses: actions/setup-java@v1
          with:
            java-version: 20
        - name: Build with Maven
          run: mvn -B package --file pom.xml
        - name: Test with Maven
          run: mvn -B test --file pom.xml